# Generated by Django 4.2.7 on 2023-11-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMSystem', '0002_alter_performancehistory_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancehistory',
            name='average_response_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='performancehistory',
            name='fulfillment_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='performancehistory',
            name='on_time_delivery_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='performancehistory',
            name='quality_rating_avg',
            field=models.FloatField(default=0.0),
        ),
    ]
